triggers:
- envs: []
  name: pristine bard
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-08 05:00:00
  status: active
  variables: {}
